# Generated by Django 4.2.21 on 2025-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='guest_capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
