# Generated by Django 4.2.21 on 2025-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_alter_listing_guest_capacity_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
